<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3GBRILF" failures="1" tests="8" name="com.nhom4.ProductTest" time="161.379" errors="0" timestamp="2024-12-03T16:52:32 ICT" skipped="0">
  <testcase classname="com.nhom4.ProductTest" name="loginTest" time="2.066"/>
  <testcase classname="com.nhom4.ProductTest" name="updateProductTest" time="1.455"/>
  <testcase classname="com.nhom4.ProductTest" name="updateProductTest" time="61.516"/>
  <testcase classname="com.nhom4.ProductTest" name="updateProductTest" time="61.407"/>
  <testcase classname="com.nhom4.ProductTest" name="updateProductTest" time="1.366"/>
  <testcase classname="com.nhom4.ProductTest" name="updateProductTest" time="1.472"/>
  <testcase classname="com.nhom4.ProductTest" name="updateProductTest" time="31.092">
    <failure message="expected [Giá phải lớn hơn 0] but found [Error
An unexpected error occurred
OK]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Giá phải lớn hơn 0] but found [Error
An unexpected error occurred
OK]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.nhom4.ProductTest.updateProductTest(ProductTest.java:255)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- updateProductTest -->
  <testcase classname="com.nhom4.ProductTest" name="updateProductTest" time="1.005"/>
</testsuite> <!-- com.nhom4.ProductTest -->
